name: OpenMandriva RPM Build

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build-package:
    runs-on: ubuntu-latest
    
    container:
      image: docker.io/openmandriva/cooker:latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Install Build Tools
        run: |
          dnf clean all
          dnf makecache
          dnf install -y rpm-build rpmdevtools dnf-plugins-core abb

      - name: Install Build Deps
        run: |
          dnf builddep -y mangowm.spec

      - name: Execute Build
        run: |
          abb build
          
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: mangowm
          path: RPMS/**/*.rpm
          if-no-files-found: error
          compression-level: 6

